name: JavaFX CI/CD with EXE Release

on:
  push:
    tags:
      - 'v*'   # triggers on version tags like v1.0.0
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 123456789
          MYSQL_DATABASE: ljsa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Wait for MySQL
        run: |
          for /l %%i in (1,1,30) do (
            mysqladmin ping -h127.0.0.1 -uroot -p123456789 --silent && exit /b 0
            timeout /t 2 >nul
          )

      - name: Import SQL schema
        run: |
          choco install mysql --params "'/port:3306 /rootpassword:123456789 /installdir:C:\mysql'" -y
          "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -h127.0.0.1 -uroot -p123456789 ljsa < ljsa.sql

      - name: Build with Maven
        run: mvn -B clean package -DskipTests --file pom.xml

      - name: Install Launch4j
        run: choco install launch4j -y

      - name: Package JAR into EXE
        run: |
          mkdir dist
          launch4j ^
            --dont-wrapJar ^
            --outfile dist/ljsa.exe ^
            --jar target/*.jar ^
            --mainClass com.manasseh.ljsa.Main ^
            --chdir . ^
            --errTitle "LJSA Error" ^
            --supportUrl "https://github.com/${{ github.repository }}" ^
            --headerType gui

      - name: Upload artifact (.exe)
        uses: actions/upload-artifact@v4
        with:
          name: ljsa-exe
          path: dist/ljsa.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ljsa.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
